### ISSUE TITLE
レビュー

### ISSUE THREAD

**Issue by MozyOk** [Delgadito-bamboo/pomodoro#1]
# index.js
index.js でシンプルに Timerを呼び出しているのはグッドですね。
短くてとてもわかりやすいです。

この部分の引数を渡す部分は、意味の通りに順番がきちんと並んでいるので、
それに合わせて変数の宣言部分の順番も揃えると親切かもしれませんね。

https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/index.js#L7

ここら辺も同様です
https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L5-L11

---

# timer.js
この部分ですが、処理をよく見てみると共通部分が見えてきませんか?
https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L21-L36

以下の部分ですね。
```
if(this.isWorkTime && this.durationTime === 0){ 
       this.durationTime = 10; 
       this.onTick = true; 
       this.interval = setInterval(this.tick,1000);
```
条件の一つにnotがついて、durationTimeの数字が違うだけなので、
関数化などをして、外からうまくdurationTimeを渡してあげる作りにするとシンプルにできそうですよね。
ここの共通化の方法を考えてみると一段進歩があると思います。😋
条件に関してもうまく共通化できるかどうかを考えてみましょう〜

---

この部分が一行で行なっている処理が長いので
右辺を独立した関数なりに分割するのがいいかもですね。
関数名はぱっとみて何やっているのかがわかる名前をつけるとより良いですね。

https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L41

---

この辺りも何か匂ってきますね。
分岐の中で同じような処理をしている場合は？ そう。まとめることができそうですよね。
先ほどと同じく、共通部分が見えてきたらまとめることできないかなぁと考えてみるとグッドです〜

https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L51-L63

# 総評
きちんとインデントがあっていたり、ファイル分割などもわかりやすくできているので
どんどん書いていきましょう〜。
あとは、このGitHub上にはたくさんのサンプルがあるので、いろんなコードを眺めてみて、
どんなファイル分割の仕方をしていて、どんな関数の分割をしているのか、どういう共通化が行われているのかをみてみたりして、
良いコードとは何かを考えてみると良いかもしれませんね。 👏

**Comment by arakitakashi** [comment]
**mozyさん
こんなご丁寧にありがとうございます！
いただいたコメントから自分なりに修正してみました。
下記は私のメモ書きです。**

> # index.js
> index.js でシンプルに Timerを呼び出しているのはグッドですね。
> 短くてとてもわかりやすいです。
> 
> この部分の引数を渡す部分は、意味の通りに順番がきちんと並んでいるので、
> それに合わせて変数の宣言部分の順番も揃えると親切かもしれませんね。
> 
> https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/index.js#L7
> 
> ここら辺も同様です
> https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L5-L11

**確かにここ雑になってました。
こういう順番や一貫性といったところにも気を付けるということがわかってよかったです。
修正しました**

> 
> # timer.js
> この部分ですが、処理をよく見てみると共通部分が見えてきませんか?
> https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L21-L36
> 
> 以下の部分ですね。
> 
> ```
> if(this.isWorkTime && this.durationTime === 0){ 
>        this.durationTime = 10; 
>        this.onTick = true; 
>        this.interval = setInterval(this.tick,1000);
> ```
> 
> 条件の一つにnotがついて、durationTimeの数字が違うだけなので、
> 関数化などをして、外からうまくdurationTimeを渡してあげる作りにするとシンプルにできそうですよね。
> ここの共通化の方法を考えてみると一段進歩があると思います。😋
> 条件に関してもうまく共通化できるかどうかを考えてみましょう〜
> 
> この部分が一行で行なっている処理が長いので
> 右辺を独立した関数なりに分割するのがいいかもですね。
> 関数名はぱっとみて何やっているのかがわかる名前をつけるとより良いですね。
> 
> https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L41
> 
> この辺りも何か匂ってきますね。
> 分岐の中で同じような処理をしている場合は？ そう。まとめることができそうですよね。
> 先ほどと同じく、共通部分が見えてきたらまとめることできないかなぁと考えてみるとグッドです〜
> 
> https://github.com/Delgadito-bamboo/pomodoro/blob/f40723c84ec32e23ade7e37d082d4ccae5da50b2/timer.js#L51-L63
> 

**setStart, setStop , displayTime として関数を外だししました。
こういう共通部分の表現の仕方が大事なんですね。
自分としての課題は「条件の共通化」というところがどうやればいいのか思いつきませんでした。。。Slackで質問させていただければと思ってます。**

> # 総評
> きちんとインデントがあっていたり、ファイル分割などもわかりやすくできているので
> どんどん書いていきましょう〜。
> あとは、このGitHub上にはたくさんのサンプルがあるので、いろんなコードを眺めてみて、
> どんなファイル分割の仕方をしていて、どんな関数の分割をしているのか、どういう共通化が行われているのかをみてみたりして、
> 良いコードとは何かを考えてみると良いかもしれませんね。 👏

**ありがとうございます！こんなご丁寧に見ていただけて本当にありがたいです。
ほかのコードも参考にしながら、感覚だったり技術をつかんでいこうと思います！**
